Update check_galera_cluster

diff --git a/check_galera_cluster b/check_galera_cluster
--- a/check_galera_cluster
+++ b/check_galera_cluster
@@ -1,146 +1,77 @@
 #!/bin/bash
 
+################################################
+# Title: Check Galera Cluster 
+# Description: Local check for check_mk
+#                to monitor Galera Cluster.
+#                 Fork from https://github.com/fridim/nagios-plugin-check_galera_cluster Version 1.1.4
+# Author: Alessandro Dolci <dolci.alessandro94@gmail.com>, Guillaume Coré <fridim@onfi.re>, 
+#         Ales Nosek <ales.nosek@gmail.com>, Staf Wagemakers <staf@wagemakers.be>
+# Creation: 08/08/2018
+# Version: 0.1 (08/08/2018) - Creation (adolci)
+#
+################################################
 
-PROGNAME=`basename $0`
-VERSION="Version 1.1.4"
-AUTHOR="Guillaume Coré <fridim@onfi.re>, Ales Nosek <ales.nosek@gmail.com>, Staf Wagemakers <staf@wagemakers.be>"
+##### THRESHOLDS #######
+# Sets minimum number of nodes in the cluster when WARNING is raised.
+warn=2
+# Sets minimum number of nodes in the cluster when CRITICAL is raised.
+crit=2
+# Sets critical value of wsrep_flow_control_paused (default is 0.1).
+fcp=0.1
+# Rise WARNING if the node is not primary/master (TRUE, FALSE)
+primary="TRUE"
+########################
 
 ST_OK=0
 ST_WR=1
 ST_CR=2
 ST_UK=3
 
-warnAlerts=0
-critAlerts=0
-unknAlerts=0
+check_name="check_galera"
+check_status=$check_name"_status"
+check_node=$check_name"_node"
+check_fcp=$check_name"_fcp"
+check_primary=$check_name"_primary"
 
+stateFile=$MK_VARDIR/$check_name
 
-print_version() {
-  echo "$VERSION $AUTHOR"
-}
-
-print_help() {
-  print_version $PROGNAME $VERSION
-  echo ""
-  echo "$PROGNAME is a Nagios plugin to monitor Galera cluster status."
-  echo ""
-  echo "$PROGNAME [-u USER] [-p PASSWORD] [-H HOST] [-P PORT] [-m file] [-w SIZE] [-c SIZE] [-s statefile] [-f FLOAT] [-0]"
-  echo ""
-  echo "Options:"
-  echo "  u)"
-  echo "    MySQL user."
-  echo "  p)"
-  echo "    MySQL password."
-  echo "  H)"
-  echo "    MySQL host."
-  echo "  P)"
-  echo "    MySQL port."
-  echo "  m)"
-  echo "    MySQL extra my.cnf configuration file."
-  echo "  w)"
-  echo "    Sets minimum number of nodes in the cluster when WARNING is raised. (default is same as critical)."
-  echo "  c)"
-  echo "    Sets minimum number of nodes in the cluster when CRITICAL is raised. (default is 2)."
-  echo "  f)"
-  echo "    Sets critical value of wsrep_flow_control_paused (default is 0.1)."
-  echo "  0)"
-  echo "    Rise CRITICAL if the node is not primary"
-  echo "  s)"
-  echo "    Create state file, detect disconnected nodes"
-  exit $ST_UK
-}
-
-# default values
-crit=2
-fcp=0.1
+param_mysql="--defaults-extra-file=$MK_CONFDIR/mysql.cfg"
 
 check_executable() {
     if [ -z "$1" ]; then
-        echo "check_executable: no parameter given!"
+        echo "$ST_UK $check_status UNKNOWN: check_executable: no parameter given!"
+        echo "$ST_UK $check_fcp UNKNOWN: check_executable: no parameter given!"
+        echo "$ST_UK $check_node UNKNOWN: check_executable: no parameter given!"
+        echo "$ST_UK $check_primary UNKNOWN: check_executable: no parameter given!"
         exit $ST_UK
     fi
 
     if ! command -v "$1" &>/dev/null; then
-        echo "UNKNOWN: Cannot find $1"
+        echo "$ST_UK $check_status UNKNOWN: Cannot find $1"
+        echo "$ST_UK $check_fcp UNKNOWN: Cannot find $1"
+        echo "$ST_UK $check_node UNKNOWN: Cannot find $1"
+        echo "$ST_UK $check_primary UNKNOWN: Cannot find $1"
         exit $ST_UK
     fi
 }
 
+#
+# verify check requirments 
+#
+
 check_executable mysql
 check_executable bc
-
-while getopts “hvu:p:H:P:w:c:f:m:s:0” OPTION; do
-  case $OPTION in
-    h)
-      print_help
-      exit $ST_UK
-      ;;
-    v)
-      print_version $PROGNAME $VERSION
-      exit $ST_UK
-      ;;
-    u)
-      mysqluser=$OPTARG
-      ;;
-    p)
-      password=$OPTARG
-      ;;
-    H)
-      mysqlhost=$OPTARG
-      ;;
-    P)
-      port=$OPTARG
-      ;;
-    m)
-      myconfig=$OPTARG
-      ;;
-    w)
-      warn=$OPTARG
-      ;;
-    c)
-      crit=$OPTARG
-      ;;
-    f)
-      fcp=$OPTARG
-      ;;
-    0)
-      primary='TRUE'
-      ;;
-    s)
-      stateFile=$OPTARG
-      ;;
-    ?)
-      echo "Unknown argument: $1"
-      print_help
-      exit $ST_UK
-      ;;
-  esac
-done
-
-if [ -z "$warn" ]; then
-  warn=$crit
-fi
-
-create_param() {
-  if [ -n "$2" ]; then
-    echo $1$2
-  fi
-}
-
-param_mysqlhost=$(create_param -h "$mysqlhost")
-param_port=$(create_param -P "$port")
-param_mysqluser=$(create_param -u "$mysqluser")
-param_password=$(create_param -p "$password")
-param_configfile=$(create_param --defaults-extra-file= "$myconfig")
-
-param_mysql="$param_mysqlhost $param_port $param_mysqluser $param_password $param_configfile"
 
 #
 # verify the database connection
 #
 
 mysql $param_mysql -B -N  -e '\s;' >/dev/null 2>&1 || {
-  echo "CRITICAL: mysql connection check failed"
+  echo "$ST_CR $check_status CRITICAL: mysql connection check failed"
+  echo "$ST_CR $check_fcp CRITICAL: mysql connection check failed"
+  echo "$ST_CR $check_node CRITICAL: mysql connection check failed"
+  echo "$ST_CR $check_primary CRITICAL: mysql connection check failed"
   exit $ST_CR
 }
 
@@ -151,7 +82,10 @@ mysql $param_mysql -B -N  -e '\s;' >/dev/null 2>&1 || {
 rClusterStateUuid=$(mysql $param_mysql -B -N -e "show status like 'wsrep_cluster_state_uuid'; "|cut -f 2)
 
 if [ -z "$rClusterStateUuid" ]; then
-  echo "CRITICAL: node is not part of a cluster"
+  echo "$ST_CR $check_status CRITICAL: node is not part of a cluster"
+  echo "$ST_CR $check_fcp CRITICAL: node is not part of a cluster"
+  echo "$ST_CR $check_node CRITICAL: node is not part of a cluster"
+  echo "$ST_CR $check_primary CRITICAL: node is not part of a cluster"
   exit $ST_CR
 fi
 
@@ -164,50 +98,56 @@ rLocalStateComment=$(mysql $param_mysql -B -N -e "show status like 'wsrep_local_
 rIncommingAddresses=$(mysql $param_mysql -B -N -e "show global status like 'wsrep_incoming_addresses';"|cut -f 2)
   
 if [ -z "$rFlowControl" ]; then
-  echo "UNKNOWN: wsrep_flow_control_paused is empty"
-  unknAlerts=$(($unknAlerts+1))
+  out_fcp=1
+  echo "$ST_UK $check_fcp UNKNOWN: wsrep_flow_control_paused is empty"
 fi
 
-if [ $(echo "$rFlowControl > $fcp" | bc) = 1 ]; then
-  echo "CRITICAL: wsrep_flow_control_paused is > $fcp"
-  critAlerts=$(($criticalAlerts+1))
+if [ $(echo "$rFlowControl > $fcp" | bc) = 1 ] && [ -z $out_fcp ]; then
+  echo "$ST_CR $check_fcp count=$rFlowControl;$fcp;$fcp;0 CRITICAL: wsrep_flow_control_paused is $rFlowControl (> $fcp)"
+else
+  echo "$ST_OK $check_fcp count=$rFlowControl;$fcp;$fcp;0 OK: wsrep_flow_control_paused is $rFlowControl (< $fcp)"
 fi
 
 if [ "$primary" = 'TRUE' ]; then
   if [ "$rClusterStatus" != 'Primary' ]; then
-    echo "CRITICAL: node is not primary (wsrep_cluster_status)"
-    critAlerts=$(($criticalAlerts+1))
+    echo "$ST_WR $check_primary count=$ST_WR;$ST_WR;$ST_WR;0 WARNING: node is not primary (wsrep_cluster_status)"
+  else
+    echo "$ST_OK $check_primary count=$ST_OK;$ST_WR;$ST_WR;0 OK: node is primary (wsrep_cluster_status)"
   fi
 fi
 
 if [ "$rReady" != 'ON' ]; then
-  echo "CRITICAL: node is not ready (wsrep_ready)"
-  critAlerts=$(($criticalAlerts+1))
+  echo "$ST_CR $check_status count=$ST_CR;$ST_WR;$ST_CR;0 CRITICAL: node is not ready (wsrep_ready)"
+  out_status=1
 fi
 
-if [ "$rConnected" != 'ON' ]; then
-  echo "CRITICAL: node is not connected (wsrep_connected)"
-  critAlerts=$(($criticalAlerts+1))
+if [ "$rConnected" != 'ON' ] && [ -z $out_status ]; then
+  echo "$ST_CR $check_status count=$ST_CR;$ST_WR;$ST_CR;0 CRITICAL: node is not connected (wsrep_connected)"
+  out_status=1
 fi
 
-if [ "$rLocalStateComment" != 'Synced' ]; then
-   echo "CRITICAL: node is not synced - actual state is: $rLocalStateComment (wsrep_local_state_comment)"
-   critAlerts=$(($criticalAlerts+1))
+if [ "$rLocalStateComment" != 'Synced' ] && [ -z $out_status ]; then
+   echo "$ST_CR $check_status count=$ST_CR;$ST_WR;$ST_CR;0 CRITICAL: node is not synced - actual state is: $rLocalStateComment (wsrep_local_state_comment)"
+fi
+
+if [ "$rLocalStateComment" == 'Synced' ] && [ -z $out_status ]; then
+   echo "$ST_OK $check_status count=$ST_OK;$ST_WR;$ST_CR;0 OK: node is synced - (wsrep_local_state_comment)"
 fi
 
 if [ $rClusterSize -gt $warn ]; then
   # only display the ok message if the state check not enabled
   if [ -z "$stateFile" ]; then
-    echo "OK: number of NODES = $rClusterSize (wsrep_cluster_size)"
+    echo "$ST_OK $check_node count=$rClusterSize;$warn;$crit;0 OK: number of NODES = $rClusterSize (wsrep_cluster_size)"
   fi
 elif [ $rClusterSize  -le $crit ]; then
-  echo "CRITICAL: number of NODES = $rClusterSize (wsrep_cluster_size)"
-  critAlerts=$(($criticalAlerts+1))
+    echo "$ST_CR $check_node count=$rClusterSize;$warn;$crit;0 CRITICAL: number of NODES = $rClusterSize (wsrep_cluster_size)"
+    exit $ST_CR
 elif [ $rClusterSize -le $warn ]; then
-    echo "WARNING: number of NODES = $rClusterSize (wsrep_cluster_size)"
-    warnAlerts=$(($warnAlerts+1))
-  else
-   exit $ST_UK
+    echo "$ST_WR $check_node count=$rClusterSize;$warn;$crit;0 WARNING: number of NODES = $rClusterSize (wsrep_cluster_size)"
+    exit $ST_WR
+else
+    echo "$ST_UK $check_node count=0;$warn;$crit;0 UNKNOWN: number of NODES undefined [$rClusterSize] (wsrep_cluster_size)"
+    exit $ST_UK
 fi
 
 #
@@ -219,9 +159,7 @@ if [ ! -z "$stateFile" ]; then
   touch $stateFile
 
   if [ $? != "0" ]; then
-
-    echo "UNKNOWN: stateFile \"$stateFile\" is not writeable"
-    unknAlerts=$(($unknAlerts+1))
+    echo "$ST_UK $check_node count=0;$warn;$crit;0 UNKNOWN: stateFile \"$stateFile\" is not writeable)"
 
   else
 
@@ -247,14 +185,13 @@ if [ ! -z "$stateFile" ]; then
       if [ $maxClusterSize -eq  $rClusterSize ]; then
         if [ $maxClusterSize -eq 1 ]; then
             if [ $crit -eq 0 -a  $warn -eq 0 ]; then
-              echo "OK: running single-node database cluster"
+              echo "$ST_OK $check_node count=$rClusterSize;$warn;$crit;0 OK: running single-node database cluster"
             fi
         else
-            echo "OK: running redundant $rClusterSize online / $maxClusterSize total"
+          echo "$ST_OK $check_node count=$rClusterSize;$warn;$crit;0 OK: running redundant $rClusterSize online / $maxClusterSize total"
         fi
       else
-            echo "WARNING: redundant  $rClusterSize online / $maxClusterSize  total, missing peers: $missingNodes" 
-            warnAlerts=$(($warnAlerts+1))
+        echo "$ST_WR $check_node count=$rClusterSize;$warn;$crit;0 WARNING: redundant  $rClusterSize online / $maxClusterSize  total, missing peers: $missingNodes"
       fi
   
     fi # rConnected
@@ -262,14 +199,3 @@ if [ ! -z "$stateFile" ]; then
   fi # -w stateFile
 
 fi # -z stateFile
-
-
-#
-# exit
-#
-
-[ "$critAlerts" -gt "0" ] && exit $ST_CR
-[ "$unknAlerts" -gt "0" ] && exit $ST_UK
-[ "$warnAlerts" -gt "0" ] && exit $ST_WR
-
-exit 0
